### ISSUE TITLE
Error to install on Python3.7

### ISSUE THREAD

**Issue by dunossauro** [avanzzzi/hypy#20]
Comand: `pip install hypy`

Traceback:

```Python
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_dmgc9ed/hypy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_dmgc9ed/hypy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-_dmgc9ed/hypy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_dmgc9ed/hypy/setup.py", line 8, in <module>
        execfile('hypy/_version.py', _version)
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dunossauro** [comment]
Create a repo on pypi

**Comment by avanzzzi** [comment]
Done

hypy can be found as hypy3 in pypi
